In [3]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sys

def readXYZfile(filename, Separator):
    data = [[],[],[],[],[],[]]
    f = open(filename, 'r')
    line = f.readline()
    num_data = 0
    while line:
        x,y,z,r,g,b = line.split(Separator)
        data[0].append(x)
        data[1].append(y)
        data[2].append(z)
        data[3].append(r)
        data[4].append(g)
        data[5].append(b)
        num_data += 1
        line = f.readline()
    f.close()

    x = [ float(x) for x in data[0]]
    y = [ float(y) for y in data[1]]
    z = [ float(z) for z in data[2]]
    r = [ int(r) for r in data[3]]
    g = [ int(g) for g in data[4]]
    b = [ int(b) for b in data[5]]
    print(f'The number of read points: \n{num_data}')
    #print(min(r), max(r))
    point = [x,y,z,r,g,b]
    return point

filename = '/home/shuai_cheng/Documents/Repositories/Learning/Stanford3dDataset_v1.2_Aligned_Version/Area_1/conferenceRoom_1/conferenceRoom_1.txt'
item = filename.split('/')[-1].split('_')[0]
print(f'Item or instance is: {item}')
data = readXYZfile(filename, ' ')

In [5]:
def displayPoint(data, title):
    if len(data[0]) > 20000:
        sys.exit('Too many points!')

    fig = plt.figure()
    ax = Axes3D(fig)
    ax.set_title(title)
    ax.scatter3D(data[0], data[1], data[2], c='r', marker='.')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')
    plt.show()

In [7]:
displayPoint(data, item)

SystemExit: Too many points!

In [29]:
import os
import sys
import h5py
import numpy as np

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(BASE_DIR)
DATA_DIR = os.path.join(BASE_DIR, 'indoor3d_sem_seg_hdf5_data')
f = h5py.File('/home/shuai_cheng/Documents/Repositories/Learning/indoor3d_sem_seg_hdf5_data/ply_data_all_0.h5', 'r')
print([key for key in f.keys()])
print(f['data'].shape)
#print(f['data'][0])
#print(type(f['data']))
print(f['label'].shape)
#print(f['label'][0][:10])
#print(type(f['label']))

npdata = np.array(f['data'])
print(npdata.shape)
#print(type(npdata))

['data', 'label']
(1000, 4096, 9)
(1000, 4096)
(1000, 4096, 9)


In [1]:
import h5py

f = h5py.File('/home/shuai_cheng/Documents/Repositories/data/modelnet40_ply_hdf5_2048/ply_data_train4.h5', 'r')
for key in f.keys():
    print(f[key].name, f[key].shape)
print(min(f['label']), max(f['label']))

/data (1648, 2048, 3)
/faceId (1648, 2048)
/label (1648, 1)
/normal (1648, 2048, 3)
[0] [39]


In [7]:
import h5py

f = h5py.File('/home/shuai_cheng/Documents/Repositories/data/modelnet40_ply_hdf5_2048/ply_data_test1.h5', 'r')
for key in f.keys():
    print(f[key].name, f[key].shape)
print(min(f['label']), max(f['label']))

/data (420, 2048, 3)
/faceId (420, 2048)
/label (420, 1)
/normal (420, 2048, 3)
[0] [39]


In [6]:
# Markov Chain
import numpy as np

matrix = np.matrix([
[0.9,0.075,0.025],
[0.15,0.8,0.05],
[0.25,0.25,0.5]], dtype=float)

vector1 = np.matrix([
[0.7, 0.2, 0.1]], dtype=float)

for i in range(100):
    vector1 = vector1*matrix
    matrix = matrix*matrix
    print(f'Current round: {i+1} \n Vector:\n {vector1}\n Matrix:\n {matrix}')

Current round: 1 
 Vector:
 [[0.685  0.2375 0.0775]]
 Matrix:
 [[0.8275  0.13375 0.03875]
 [0.2675  0.66375 0.06875]
 [0.3875  0.34375 0.26875]]
Current round: 2 
 Vector:
 [[0.6604 0.2759 0.0637]]
 Matrix:
 [[0.73555  0.212775 0.051675]
 [0.42555  0.499975 0.074475]
 [0.51675  0.372375 0.110875]]
Current round: 3 
 Vector:
 [[0.63608344 0.30218    0.06173656]]
 Matrix:
 [[0.65828326 0.28213131 0.05958543]
 [0.56426262 0.36825403 0.06748335]
 [0.5958543  0.33741675 0.06672895]]
Current round: 4 
 Vector:
 [[0.62601795 0.31156901 0.06241304]]
 Matrix:
 [[0.62803724 0.30972343 0.06223933]
 [0.61944687 0.3175772  0.06297594]
 [0.6223933  0.3148797  0.062727  ]]
Current round: 5 
 Vector:
 [[0.62500849 0.31249224 0.06249927]]
 Matrix:
 [[0.62502532 0.31247685 0.06249783]
 [0.6249537  0.31254233 0.06250397]
 [0.62497828 0.31251986 0.06250186]]
Current round: 6 
 Vector:
 [[0.625  0.3125 0.0625]]
 Matrix:
 [[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round

In [1]:
from dataset import *
    
train_dataset = ModelNetDataset(root=BASE_DIR)
seg_dataset = S3DISDataset(root=BASE_DIR)


In [2]:
train_dataloader = DataLoader(train_dataset, batch_size=64)
for i, (point_cloud, label) in enumerate(train_dataloader):
    break

In [3]:
print(point_cloud.shape, label.shape)

torch.Size([64, 2048, 3]) torch.Size([64, 1])


In [7]:
import torch.nn as nn
import torch.nn.functional as F

class PointNet(nn.Module):
    
    def __init__(self, num_class=train_dataset.num_classes, num_point=train_dataset.num_points):
        super(PointNet, self).__init__()
        # Conv1d works as a Linear layer
        self.conv1 = nn.Conv1d(3, 64, 1)
        self.conv2 = nn.Conv1d(64, 64, 1)
        self.conv3 = nn.Conv1d(64, 128, 1)
        self.conv4 = nn.Conv1d(128, 1024, 1)
        self.pool = nn.MaxPool1d(num_point)
        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(64)
        self.bn3 = nn.BatchNorm1d(128)
        self.bn4 = nn.BatchNorm1d(1024)
        self.fc1 = nn.Linear(1024, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, num_class)
        self.bn5 = nn.BatchNorm1d(512)
        self.bn6 = nn.BatchNorm1d(256)
        self.dropout = nn.Dropout(p=0.3)  # keep ratio = 0.7


    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool(x)
        x = F.relu(self.bn5(self.fc1(x.transpose(2,1)).squeeze()))
        x = F.relu(self.bn6(self.dropout(self.fc2(x))))
        x = self.fc3(x)
        return x

net = PointNet()
output = net(point_cloud.transpose(2, 1))
print(output.shape)

torch.Size([64, 40])


In [37]:
import torch
m = nn.Conv1d(in_channels=16, out_channels=33, kernel_size=3, stride=3)
input = torch.randn(20, 16, 50)  # (batch, channel, length of sequence)
output = m(input)
print(output.shape)

torch.Size([20, 33, 16])


In [4]:
from model import *

